version: '3.8'

services:
  voice-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./audio:/app/audio
      - ./reports:/app/reports
      - ./etalons:/app/etalons
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - PYTHONPATH=/app
    working_dir: /app/app